sudo: required

language: python

python:
    - "3.8"
    
services:
    - docker

install:
  - pip install -r requirements.txt

script:
  - docker build -t nitesh99sharma/python-travis:$TRAVIS_TAG .
  - docker images 

deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
        branch: main



