sudo: required
dist: xenial
language: python
python:
- '3.8'
os:
- linux
services:
- docker
env:
  global:
  - GIT_SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_128424e37458_key -iv $encrypted_128424e37458_iv
  -in gcp-credentials.json.enc -out gcp-credentials.json -d
- chmod +x cluster_configuration.sh
install:
- pip install -r requirements.txt
- "./cluster_configuration.sh"
script:
- echo "hello"
after_success:
- echo "deployment started......."
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: main
