apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      name: py-app-pod
      labels:
         app: py-app
    spec:
        containers:
        - name: py-app-container
          image: nitesh99sharma/python-travis:v3
          imagePullPolicy: Always
          ports:
          - containerPort: 8080